/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as LecturerIndexRouteImport } from './routes/lecturer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentPaymentsRouteImport } from './routes/student/payments'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as LecturerStudentsRouteImport } from './routes/lecturer/students'
import { Route as LecturerResultsRouteImport } from './routes/lecturer/results'
import { Route as LecturerReportsRouteImport } from './routes/lecturer/reports'
import { Route as LecturerCoursesRouteImport } from './routes/lecturer/courses'
import { Route as LecturerAttendanceRouteImport } from './routes/lecturer/attendance'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminFeesRouteImport } from './routes/admin/fees'
import { Route as AdminFacultiesRouteImport } from './routes/admin/faculties'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as StudentResultsIndexRouteImport } from './routes/student/results/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerIndexRoute = LecturerIndexRouteImport.update({
  id: '/lecturer/',
  path: '/lecturer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPaymentsRoute = StudentPaymentsRouteImport.update({
  id: '/student/payments',
  path: '/student/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerStudentsRoute = LecturerStudentsRouteImport.update({
  id: '/lecturer/students',
  path: '/lecturer/students',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerResultsRoute = LecturerResultsRouteImport.update({
  id: '/lecturer/results',
  path: '/lecturer/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerReportsRoute = LecturerReportsRouteImport.update({
  id: '/lecturer/reports',
  path: '/lecturer/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerCoursesRoute = LecturerCoursesRouteImport.update({
  id: '/lecturer/courses',
  path: '/lecturer/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerAttendanceRoute = LecturerAttendanceRouteImport.update({
  id: '/lecturer/attendance',
  path: '/lecturer/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/admin/fees',
  path: '/admin/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin/faculties',
  path: '/admin/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsIndexRoute = StudentResultsIndexRouteImport.update({
  id: '/student/results/',
  path: '/student/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/attendance': typeof LecturerAttendanceRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/reports': typeof LecturerReportsRoute
  '/lecturer/results': typeof LecturerResultsRoute
  '/lecturer/students': typeof LecturerStudentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/admin': typeof AdminIndexRoute
  '/lecturer': typeof LecturerIndexRoute
  '/student': typeof StudentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/student/results': typeof StudentResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/attendance': typeof LecturerAttendanceRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/reports': typeof LecturerReportsRoute
  '/lecturer/results': typeof LecturerResultsRoute
  '/lecturer/students': typeof LecturerStudentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/admin': typeof AdminIndexRoute
  '/lecturer': typeof LecturerIndexRoute
  '/student': typeof StudentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/student/results': typeof StudentResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/attendance': typeof LecturerAttendanceRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/reports': typeof LecturerReportsRoute
  '/lecturer/results': typeof LecturerResultsRoute
  '/lecturer/students': typeof LecturerStudentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/payments': typeof StudentPaymentsRoute
  '/admin/': typeof AdminIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/student/results/': typeof StudentResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/fees'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/lecturer/attendance'
    | '/lecturer/courses'
    | '/lecturer/reports'
    | '/lecturer/results'
    | '/lecturer/students'
    | '/student/courses'
    | '/student/payments'
    | '/admin'
    | '/lecturer'
    | '/student'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/student/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/fees'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/lecturer/attendance'
    | '/lecturer/courses'
    | '/lecturer/reports'
    | '/lecturer/results'
    | '/lecturer/students'
    | '/student/courses'
    | '/student/payments'
    | '/admin'
    | '/lecturer'
    | '/student'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/student/results'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/fees'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/lecturer/attendance'
    | '/lecturer/courses'
    | '/lecturer/reports'
    | '/lecturer/results'
    | '/lecturer/students'
    | '/student/courses'
    | '/student/payments'
    | '/admin/'
    | '/lecturer/'
    | '/student/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/student/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LecturerAttendanceRoute: typeof LecturerAttendanceRoute
  LecturerCoursesRoute: typeof LecturerCoursesRoute
  LecturerReportsRoute: typeof LecturerReportsRoute
  LecturerResultsRoute: typeof LecturerResultsRoute
  LecturerStudentsRoute: typeof LecturerStudentsRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentPaymentsRoute: typeof StudentPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LecturerIndexRoute: typeof LecturerIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  StudentResultsIndexRoute: typeof StudentResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/': {
      id: '/lecturer/'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/payments': {
      id: '/student/payments'
      path: '/student/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof StudentPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/students': {
      id: '/lecturer/students'
      path: '/lecturer/students'
      fullPath: '/lecturer/students'
      preLoaderRoute: typeof LecturerStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/results': {
      id: '/lecturer/results'
      path: '/lecturer/results'
      fullPath: '/lecturer/results'
      preLoaderRoute: typeof LecturerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/reports': {
      id: '/lecturer/reports'
      path: '/lecturer/reports'
      fullPath: '/lecturer/reports'
      preLoaderRoute: typeof LecturerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/courses': {
      id: '/lecturer/courses'
      path: '/lecturer/courses'
      fullPath: '/lecturer/courses'
      preLoaderRoute: typeof LecturerCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/attendance': {
      id: '/lecturer/attendance'
      path: '/lecturer/attendance'
      fullPath: '/lecturer/attendance'
      preLoaderRoute: typeof LecturerAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/admin/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/admin/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results/': {
      id: '/student/results/'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  LecturerAttendanceRoute: LecturerAttendanceRoute,
  LecturerCoursesRoute: LecturerCoursesRoute,
  LecturerReportsRoute: LecturerReportsRoute,
  LecturerResultsRoute: LecturerResultsRoute,
  LecturerStudentsRoute: LecturerStudentsRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentPaymentsRoute: StudentPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  LecturerIndexRoute: LecturerIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  StudentResultsIndexRoute: StudentResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
